### PR TITLE
Added fixed command to get exit status 0/1 if hosts file is already formatted

### LINKED ISSUE #24: Add a `hostess fix --dry-run`
Some command error out when the `/etc/hosts` file is invalid (for example, when it has dupes). For scripting purposes, it would be nice to be able to check once in the beginning of a bunch of option and issue a `hostess fix`. The issue is that you can have a `hostess fix`, but it would require a possibly redundant `sudo` access if the configuration is in the expected state.

In the same sense, it would be nice if `apply` also has a `--dry-run` so that you can check before requiring `sudo`.

Imagine a script like this:

```bash
if ! hostess fix --dry-run; then
  sudo hostess fix
fi
if ! hostess apply hostess.json --dry-run; then
  sudo hostess apply hostess.json
fi
```

Of course, there's copy and paste of code, but maybe it could be done somehow via hostess calling itself with `sudo`?

### PR DESCRIPTION
**Pull request by cbednarski**
@nikolay Can you try building this and let me know if it accomplishes what you're hoping it will?

Closes #24

### CODE REVIEW

**Comment by nikolay** [comment]
I can't go beyond this, sorry:
```
$ cd /Users/username/Projects/hostess
$ make
go get github.com/golang/lint/golint
go get github.com/stretchr/testify/assert
go get golang.org/x/tools/cmd/cover
go get
go install: no install location for directory /Users/username/Projects/hostess outside GOPATH
	For more details see: go help gopath
make: *** [deps] Error 1
```

I have this:
```
$ echo $GOPATH; echo $GOBIN
/Users/username/.go
/Users/username/.go/bin
```

I'm sorry but I'm not a Go developer, and the documentation is not very helpful!

**Comment by cbednarski** [comment]
Ah .. instead of the Makefile you can try:

```
go get github.com/cbednarski/hostess
cd $GOPATH/src/github.com/cbednarski/hostess
git checkout f-hostess-fixed
go install ./cmd/hostess/hostess.go
```

I tested this and the code works but I want to make sure it hits the UX you're expecting. If you are having trouble getting this to work I can just include as-is and ship in the next release.

**Comment by nikolay** [comment]
@cbednarski Thanks! This worked but even with dupe entries, it still returns 0:

```
$ ./hostess fix -n -q
Duplicate hostname entry for domain.dev -> 127.0.0.1
Duplicate hostname entry for www.domain.dev -> 127.0.0.1
127.0.0.1 domain.dev www.domain.dev
$ echo $?
0
```

**Comment by cbednarski** [comment]
Oh, sorry! There is a new command `hostess fixed` which will change the exit code.

**Comment by nikolay** [comment]
@cbednarski Thanks! I thought that was a typo! 😄

**Comment by nikolay** [comment]
@cbednarski Work as expected! Thank you very much!

**Pull request merged**
