### PR TITLE
Support alternate install prefix

### PR DESCRIPTION
**Pull request by md5**
This will make is possible to create a Homebrew formula.

I also added a `.PHONY` as well as additional directories in case you want to add a `man` page at some point.

### CODE REVIEW

**Comment by md5** [comment]
To be clear, it would be possible to create a Homebrew formula currently from the release binaries on GitHub, but this will make it possible to have it build from source as is done for most of the other Git-based formula's I've seen in Homebrew.

**Comment by cbednarski** [comment]
Awesome, thanks for the contribution! As a caveat since the dependencies are not vendored I think you may also run into #15, which I have not had a chance to look into yet.

**Comment by md5** [comment]
@cbednarski The Homebrew formulas for Go applications list their dependencies and the require SHA directly, so I don't think the lack of vendoring should be a problem (hopefully).

**Comment by cbednarski** [comment]
@md5 Ah yeah, that came up at one point on Packer, but because we didn't vendor they had to go through and manually update / record each of our dependencies which was a lot of work. Vendoring eliminates that problem. I will get around to it at some point. :)

**Comment by md5** [comment]
I've got an first cut at a Homebrew formula here: https://github.com/md5/homebrew-core/commit/335d8f42dfdbd5498ce9f0238cc91c88a521e73e

I was able to install it with `brew install --HEAD hostess`. I don't have any more time at the moment to go further with this, but I thought I'd share.

I think it would be helpful if you could cut a new patch release that includes the latest `Makefile` changes. It also seems like something should be done to make the `deps` target play nice with a sandboxed build, but I'm not sure what the exact steps should be.

**Comment by cbednarski** [comment]
> I think it would be helpful if you could cut a new patch release that includes the latest Makefile changes. It also seems like something should be done to make the deps target play nice with a sandboxed build, but I'm not sure what the exact steps should be.

I will do this after I've had a chance to vendor the deps. Based on this strategy, with go 1.5+ you can build with the dependencies that are included in this repo instead of fetching them internally, which means the right version is already included and there is no extra deps step at build time. This was a pretty successful approach in the packer project so I think it will work well here even though it's a lot less complicated. I will try to get around to this later today.

**Comment by md5** [comment]
👍

**Comment by cbednarski** [comment]
@md5 I've added the dependency to the vendor folder so you should be able to build deterministically simply by cloning the project. I've already tagged the 0.2.0 release and published new binaries build with go 1.6.

**Comment by md5** [comment]
@cbednarski It seems like `codegangsta/cli` should be vendored at `vendor/github.com/codegangsta/cli`.

I have an updated formula here: https://github.com/md5/homebrew-core/commit/7256858834a6e712d25951b7ddb6a7f50fe3523d

It fails like so:

```console
$ brew install hostess
==> Downloading https://github.com/cbednarski/hostess/archive/v0.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/hostess-0.2.0.tar.gz
==> go build cmd/hostess/hostess.go
Last 15 lines from /Users/mike/Library/Logs/Homebrew/hostess/01.go:
2016-05-16 21:52:27 -0700

go
build
cmd/hostess/hostess.go

src/github.com/cbednarski/hostess/commands.go:10:2: cannot find package "github.com/codegangsta/cli" in any of:
	/private/tmp/hostess-20160516-3326-1520a10/hostess-0.2.0/src/github.com/cbednarski/hostess/vendor/github.com/codegangsta/cli (vendor tree)
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/private/tmp/hostess-20160516-3326-1520a10/hostess-0.2.0/src/github.com/codegangsta/cli (from $GOPATH)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by cbednarski** [comment]
Oops you're right! Sorry about that.

**Comment by cbednarski** [comment]
Check out v0.2.1 for the updated vendor. Thanks for the heads up!

**Comment by md5** [comment]
Hmm... I tried updating it (in https://github.com/md5/homebrew-core/commit/d4642fbd00ad7e0c47b45bf89e4853580d5083aa) and now I'm seeing a different error:

```
$ brew install hostess
==> Downloading https://github.com/cbednarski/hostess/archive/v0.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/hostess-0.2.1.tar.gz
==> go build cmd/hostess/hostess.go
Last 15 lines from /Users/dillm022/Library/Logs/Homebrew/hostess/01.go:
2016-05-19 11:00:19 -0700

go
build
cmd/hostess/hostess.go

cmd/hostess/hostess.go:7:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/private/tmp/hostess-20160519-34876-aomfrw/hostess-0.2.1/src/github.com/codegangsta/cli (from $GOPATH)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

```

I'm not sure why "vendor tree" is no longer being checked...

**Comment by cbednarski** [comment]
@md5 Did you clone the repo to your GOPATH? Even when the package is vendored it still needs to be in your GOPATH. The easiest way to do this is `go get github.com/cbednarski/hostess`. I just double-checked on my side and I don't have anything under `$GOPATH/github/codegangsta` and it builds just fine with `go build` and `make`.

**Comment by cbednarski** [comment]
@md5 Maybe this line https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/packer.rb#L364 ?

**Comment by md5** [comment]
If you look at the formula, it sets `GOPATH` to the directory that was expanded from the `*.tar.gz` file. It then symlinks that same directory as `src/github.com/cbednarski/hostess` to make it looks like `go get` was done: https://github.com/md5/homebrew-core/blob/d4642fbd00ad7e0c47b45bf89e4853580d5083aa/Formula/hostess.rb#L13-L16

This seems to be a pretty common pattern for Homebrew formulas for Go binaries (cf. [docker-swarm](https://github.com/Homebrew/homebrew-core/blob/f2e7286ed0d352bd770f8d5bee1e3de5bfc40fc9/Formula/docker-swarm.rb#L69-L76) for example)

The weird thing is that when I tried to build 0.2.0, it was clearly looking for the `vendor/github.com/codegangsta/cli` directory in the checkout (which didn't exist in that release because it was at `vendor/codegangsta/cli`): 

```
src/github.com/cbednarski/hostess/commands.go:10:2: cannot find package "github.com/codegangsta/cli" in any of:
    /private/tmp/hostess-20160516-3326-1520a10/hostess-0.2.0/src/github.com/cbednarski/hostess/vendor/github.com/codegangsta/cli (vendor tree)
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
    /private/tmp/hostess-20160516-3326-1520a10/hostess-0.2.0/src/github.com/codegangsta/cli (from $GOPATH)
```
But when I updated to 0.2.1, it seems `go build` stopped checking the `vendor` directory:

```
cmd/hostess/hostess.go:7:2: cannot find package "github.com/codegangsta/cli" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
    /private/tmp/hostess-20160519-34876-aomfrw/hostess-0.2.1/src/github.com/codegangsta/cli (from $GOPATH)
```

The only change I made was the URL for the source package from GitHub and the SHA-256 sum for that package.

**Pull request merged**
